# Generated by Django 5.2.17 on 2026-10-05 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroTerapeutico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="Aquí Somos Sensoriales", max_length=100),
                ),
                (
                    "horas_minimas_cancelacion",
                    models.PositiveSmallIntegerField(default=24),
                ),
                (
                    "duracion_bloque",
                    models.PositiveSmallIntegerField(
                        default=45, verbose_name="duración del bloque (minutos)"
                    ),
                ),
            ],
            options={
                "verbose_name": "centro terapéutico",
                "verbose_name_plural": "centro terapéutico",
            },
        ),
        migrations.CreateModel(
            name="BloqueHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                ("disponible", models.BooleanField(default=True)),
                (
                    "especialista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "bloque horario",
                "verbose_name_plural": "bloques horarios",
                "ordering": ["inicio"],
            },
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOLICITADA", "Solicitada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="SOLICITADA",
                        max_length=10,
                    ),
                ),
                ("motivo_consulta", models.CharField(blank=True, max_length=300)),
                (
                    "motivo_respuesta",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="motivo de rechazo o cancelación",
                    ),
                ),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("actualizada", models.DateTimeField(auto_now=True)),
                (
                    "bloque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="agenda.bloquehorario",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bloque__inicio"],
            },
        ),
    ]
